name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS Debug",
            artifact: "macos_debug.tar.xz",
            build_type: "debug",
          }
          - {
            name: "macOS Release",
            artifact: "macos_release.tar.xz",
            build_type: "release",
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update environment
        run: |
          brew install \
          libfreetype-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} -j2

      - name: Prepare Upload
        run: |
          tar cfz ${{matrix.config.artifact}} build

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}
